import Link from "next/link";
import { ArrowRight, BarChart3, CheckCircle2, MessageSquareText, ShieldCheck, Sparkles } from "lucide-react";
import { Container } from "@/components/container";
import { SectionHeading } from "@/components/section-heading";
import { ProposalCard } from "@/components/proposal-card";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { siteConfig } from "@/config/site";
import { getCommitments, getPosts, getProposals, getPublicDemandStats } from "@/lib/data";
import { formatShortDate } from "@/lib/utils";

export default async function HomePage() {
  const [proposals, commitments, stats, posts] = await Promise.all([getProposals(), getCommitments(), getPublicDemandStats(), getPosts()]);
  return <>
    <section className="relative overflow-hidden pb-16 pt-14 sm:pb-24 sm:pt-20">
      <div className="absolute inset-0 -z-10 noise"/><Container className="grid items-center gap-12 lg:grid-cols-[1.08fr_.92fr]">
        <div><Badge tone="brand">Uma nova forma de participar</Badge><h1 className="mt-6 max-w-4xl text-5xl font-semibold leading-[.98] tracking-[-.055em] sm:text-6xl lg:text-7xl">Política com escuta, compromisso e <span className="text-[var(--brand)]">prestação de contas.</span></h1><p className="mt-7 max-w-2xl text-lg leading-8 text-black/62">{siteConfig.candidate.shortBio}</p><div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/demandas" className="inline-flex h-13 items-center justify-center gap-2 rounded-full bg-[var(--brand)] px-7 font-bold text-white shadow-[0_15px_40px_rgba(18,87,69,.25)] transition hover:-translate-y-0.5 hover:bg-[var(--brand-dark)]">Envie sua demanda <ArrowRight size={18}/></Link><Link href="/propostas" className="inline-flex h-13 items-center justify-center rounded-full border border-black/10 bg-white px-7 font-bold transition hover:border-[var(--brand)]/30">Conheça as propostas</Link></div><div className="mt-9 flex flex-wrap gap-x-6 gap-y-3 text-sm text-black/55"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[var(--brand)]"/> Canal com protocolo</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[var(--brand)]"/> Dados protegidos</span><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-[var(--brand)]"/> Compromissos públicos</span></div></div>
        <div className="relative mx-auto w-full max-w-xl"><div className="absolute -left-6 top-16 h-24 w-24 rounded-full bg-[var(--accent)]/50 blur-2xl"/><div className="relative overflow-hidden rounded-[42px] border border-white/80 bg-[#173e32] p-6 text-white shadow-[0_35px_90px_rgba(20,55,44,.28)] sm:p-8"><div className="absolute inset-0 opacity-50 noise"/><div className="relative"><div className="flex items-center justify-between"><Badge className="bg-white/12 text-white">MANDATO ABERTO</Badge><Sparkles size={18} className="text-[var(--accent)]"/></div><div className="mt-16 flex items-end justify-between gap-6"><div><p className="text-sm font-medium text-white/60">{siteConfig.candidate.office}</p><h2 className="mt-2 text-4xl font-semibold tracking-[-.04em]">{siteConfig.candidate.ballotName}</h2><p className="mt-3 max-w-sm text-sm leading-6 text-white/65">{siteConfig.candidate.slogan}</p></div><div className="grid h-24 w-24 shrink-0 place-items-center rounded-[30px] bg-[var(--accent)] text-3xl font-black text-[#173e32]">{siteConfig.candidate.initials}</div></div><div className="mt-10 grid grid-cols-3 gap-3"><div className="rounded-2xl bg-white/[.08] p-4"><p className="text-2xl font-bold">{stats.total}</p><p className="mt-1 text-xs text-white/55">demandas</p></div><div className="rounded-2xl bg-white/[.08] p-4"><p className="text-2xl font-bold">{stats.cities}</p><p className="mt-1 text-xs text-white/55">municípios</p></div><div className="rounded-2xl bg-white/[.08] p-4"><p className="text-2xl font-bold">{commitments.length}</p><p className="mt-1 text-xs text-white/55">compromissos</p></div></div></div></div></div>
      </Container>
    </section>

    <section className="py-20"><Container><SectionHeading eyebrow="Prioridades" title="Propostas claras para problemas reais" description="Cada proposta deve explicar o problema, o caminho possível no Congresso e como a população poderá acompanhar o resultado."/><div className="mt-10 grid gap-5 md:grid-cols-2 lg:grid-cols-3">{proposals.slice(0,6).map(p=><ProposalCard key={p.id} proposal={p}/>)}</div><div className="mt-9 text-center"><Link href="/propostas" className="inline-flex items-center gap-2 font-bold text-[var(--brand)]">Ver todas as propostas <ArrowRight size={17}/></Link></div></Container></section>

    <section className="py-20"><Container><div className="overflow-hidden rounded-[40px] bg-[#10251d] px-6 py-12 text-white sm:px-10 lg:px-14"><SectionHeading eyebrow="Tecnologia a serviço das pessoas" title="Uma campanha que já funciona como gabinete digital" description="A plataforma organiza demandas, informa compromissos e cria uma memória pública do que foi prometido e entregue." className="[&_h2]:text-white [&_p:last-child]:text-white/60"/><div className="mt-10 grid gap-4 md:grid-cols-3"><Card className="border-white/10 bg-white/[.06] text-white shadow-none"><CardContent className="pt-6"><MessageSquareText className="text-[var(--accent)]"/><h3 className="mt-5 text-lg font-bold">Sua voz com protocolo</h3><p className="mt-2 text-sm leading-6 text-white/55">Envie uma demanda e receba um número para acompanhar o atendimento.</p></CardContent></Card><Card className="border-white/10 bg-white/[.06] text-white shadow-none"><CardContent className="pt-6"><BarChart3 className="text-[var(--accent)]"/><h3 className="mt-5 text-lg font-bold">Compromissos mensuráveis</h3><p className="mt-2 text-sm leading-6 text-white/55">Metas, indicadores e andamento apresentados em linguagem simples.</p></CardContent></Card><Card className="border-white/10 bg-white/[.06] text-white shadow-none"><CardContent className="pt-6"><ShieldCheck className="text-[var(--accent)]"/><h3 className="mt-5 text-lg font-bold">Informação oficial</h3><p className="mt-2 text-sm leading-6 text-white/55">Canal para confirmar mensagens, esclarecer boatos e proteger a população.</p></CardContent></Card></div></div></Container></section>

    <section className="py-20"><Container><div className="flex flex-col justify-between gap-6 sm:flex-row sm:items-end"><SectionHeading eyebrow="Notícias" title="Acompanhe o que está acontecendo" description="Informações oficiais, atualizações da plataforma e posicionamentos da candidata."/><Link href="/noticias" className="font-bold text-[var(--brand)]">Ver todas</Link></div><div className="mt-10 grid gap-5 lg:grid-cols-3">{posts.slice(0,3).map(post=><Link key={post.id} href={`/noticias/${post.slug}`} className="group rounded-[28px] border border-black/[.07] bg-white p-6 shadow-[0_18px_60px_rgba(27,45,38,.07)] transition hover:-translate-y-1"><Badge>{post.category}</Badge><h3 className="mt-5 text-xl font-bold tracking-[-.025em] group-hover:text-[var(--brand)]">{post.title}</h3><p className="mt-3 text-sm leading-7 text-black/55">{post.excerpt}</p><p className="mt-5 text-xs font-semibold uppercase tracking-wider text-black/35">{formatShortDate(post.publishedAt)}</p></Link>)}</div></Container></section>

    <section className="pb-10 pt-8"><Container><div className="rounded-[38px] bg-[var(--accent)] px-6 py-12 sm:px-10 lg:flex lg:items-center lg:justify-between lg:px-14"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-black/50">Participação</p><h2 className="mt-3 max-w-3xl text-3xl font-semibold tracking-[-.04em] sm:text-4xl">O que precisa mudar na sua cidade?</h2><p className="mt-4 max-w-2xl text-black/60">Compartilhe uma necessidade, sugestão ou problema. A equipe organizará as contribuições por município e tema.</p></div><Link href="/demandas" className="mt-7 inline-flex h-13 shrink-0 items-center justify-center gap-2 rounded-full bg-[#10251d] px-7 font-bold text-white lg:mt-0">Participar agora <ArrowRight size={18}/></Link></div></Container></section>
  </>;
}
