import { desc, sql } from "drizzle-orm";
import { CalendarDays, CheckSquare2, Database, FileText, MessageSquareText, Newspaper } from "lucide-react";
import { AdminPageHeader } from "@/components/admin-page-header";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent } from "@/components/ui/card";
import { getDb, hasDatabase } from "@/db";
import { commitments, demands, events, posts, proposals } from "@/db/schema";
import { formatShortDate } from "@/lib/utils";

export default async function AdminDashboard() {
  let counts = { demands:0, proposals:0, commitments:0, events:0, posts:0 };
  let latest: Array<{ id:string; protocol:string; title:string; city:string; status:string; createdAt:Date }> = [];
  if (hasDatabase()) { try { const db=getDb(); const [d,p,c,e,n] = await Promise.all([
    db.select({total:sql<number>`count(*)::int`}).from(demands), db.select({total:sql<number>`count(*)::int`}).from(proposals), db.select({total:sql<number>`count(*)::int`}).from(commitments), db.select({total:sql<number>`count(*)::int`}).from(events), db.select({total:sql<number>`count(*)::int`}).from(posts)
  ]); counts={demands:d[0]?.total||0,proposals:p[0]?.total||0,commitments:c[0]?.total||0,events:e[0]?.total||0,posts:n[0]?.total||0}; latest=await db.select({id:demands.id,protocol:demands.protocol,title:demands.title,city:demands.city,status:demands.status,createdAt:demands.createdAt}).from(demands).orderBy(desc(demands.createdAt)).limit(6); } catch {} }
  const cards=[{label:"Demandas",value:counts.demands,icon:MessageSquareText},{label:"Propostas",value:counts.proposals,icon:FileText},{label:"Compromissos",value:counts.commitments,icon:CheckSquare2},{label:"Agenda",value:counts.events,icon:CalendarDays},{label:"Notícias",value:counts.posts,icon:Newspaper}];
  return <><AdminPageHeader title="Visão geral" description="Acompanhe a operação digital e acesse rapidamente as áreas que precisam de atualização."/>{!hasDatabase() && <div className="mb-7 flex gap-4 rounded-[24px] border border-amber-200 bg-amber-50 p-5 text-amber-950"><Database className="shrink-0"/><div><h2 className="font-bold">Persistência indisponível</h2><p className="mt-1 text-sm leading-6">O site público continua no ar com conteúdo de apoio. Cadastros e sincronização do painel ficam limitados até a conexão ser restabelecida.</p></div></div>}<div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-5">{cards.map(({label,value,icon:Icon})=><Card key={label}><CardContent className="pt-6"><Icon size={20} className="text-[var(--brand)]"/><p className="mt-5 text-3xl font-bold">{value}</p><p className="mt-1 text-xs font-semibold uppercase tracking-wider text-black/35">{label}</p></CardContent></Card>)}</div><Card className="mt-7"><CardContent className="p-6"><div className="flex items-center justify-between"><h2 className="text-lg font-bold">Demandas recentes</h2><Badge>{latest.length} registros</Badge></div><div className="mt-5 overflow-x-auto"><table className="w-full min-w-[680px] text-left text-sm"><thead><tr className="border-b border-black/[.06] text-xs uppercase tracking-wider text-black/35"><th className="pb-3">Protocolo</th><th className="pb-3">Demanda</th><th className="pb-3">Município</th><th className="pb-3">Status</th><th className="pb-3">Data</th></tr></thead><tbody>{latest.map(item=><tr key={item.id} className="border-b border-black/[.05]"><td className="py-4 font-mono text-xs font-bold">{item.protocol}</td><td className="py-4 font-semibold">{item.title}</td><td className="py-4 text-black/50">{item.city}</td><td className="py-4"><Badge tone="warning">{item.status}</Badge></td><td className="py-4 text-black/45">{formatShortDate(item.createdAt)}</td></tr>)}{latest.length===0&&<tr><td colSpan={5} className="py-10 text-center text-black/40">Nenhuma demanda registrada.</td></tr>}</tbody></table></div></CardContent></Card></>;
}
